version: "3.9"
services:
  engine:
    build:
      context: .
      dockerfile: Dockerfile.engine
    container_name: ob_engine
    ports:
      - "18081:18081"   # HTTP
      - "9001:9001"     # TCP
  streamer:
    build:
      context: .
      dockerfile: Dockerfile.streamer
    container_name: ob_streamer
    depends_on:
      - engine
